import { fileURLToPath } from 'node:url'
// @ts-check
import { antfu } from '@antfu/eslint-config'
import { includeIgnoreFile } from '@eslint/compat'
import betterTailwindcss from 'eslint-plugin-better-tailwindcss'
import withNuxt from './.nuxt/eslint.config.mjs'

const gitignorePath = fileURLToPath(new URL('.gitignore', import.meta.url))

export default withNuxt(
  antfu({
    formatters: true,
  }),
  {
    rules: {
      'curly': ['error', 'multi-line', 'consistent'],
      'node/prefer-global/buffer': ['error', 'always'],
      'node/prefer-global/process': ['error', 'always'],
      'style/arrow-parens': ['error', 'always'],
      'style/brace-style': ['error', '1tbs'],
      'style/operator-linebreak': ['error', 'after', { overrides: { '?': 'before', ':': 'before' } }],
      'vue/max-attributes-per-line': ['error'],
      'vue/attributes-order': ['error', { alphabetical: true }],
    },
  },
  {
    plugins: {
      'better-tailwindcss': betterTailwindcss,
    },
    rules: {
      ...betterTailwindcss.configs.stylistic.rules,
      ...betterTailwindcss.configs.correctness.rules,
    },
    settings: {
      'better-tailwindcss': { entryPoint: 'app/assets/css/tailwind.css' },
    },
  },
  {
    files: ['pnpm-workspace.yaml'],
    rules: {
      'pnpm/yaml-enforce-settings': ['error', { settings: { shellEmulator: true } }],
    },
  },
  includeIgnoreFile(gitignorePath, 'Imported .gitignore patterns'),
  {
    ignores: [
      '.pnpm-store/', // Generated by CI workflow
      'server/db/drizzle', // Generated by Drizzle ORM
      'CLAUDE.md', // Claude Code project instructions
      '**/CLAUDE.md', // Claude Code project instructions in subdirectories
    ],
  },
)
