// @ts-check
import { antfu } from '@antfu/eslint-config'
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  antfu({
    formatters: true,
  }),
  {
    rules: {
      'curly': ['error', 'multi-line', 'consistent'],
      'node/prefer-global/buffer': ['error', 'always'],
      'node/prefer-global/process': ['error', 'always'],
      'style/arrow-parens': ['error', 'always'],
      'style/brace-style': ['error', '1tbs'],
      'style/operator-linebreak': ['error', 'after', { overrides: { '?': 'before', ':': 'before' } }],
      'vue/max-attributes-per-line': ['error'],
      'vue/attributes-order': ['error', { alphabetical: true }],
    },
  },
  {
    files: ['pnpm-workspace.yaml'],
    rules: {
      'pnpm/yaml-enforce-settings': ['error', { settings: { shellEmulator: true } }],
    },
  },
  {
    ignores: [
      '.pnpm-store/', // Generated by CI workflow
    ],
  },
)
